language: go

go:
  - '1.11'

compiler:
  - gcc
os:
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then sudo apt-get update -qq && sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev gcc-mingw-w64-x86-64; fi
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew install cunit lcov ; fi
  - mkdir -p $GOPATH/bin && curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make vendor
  - make package-all
  - ls -l ./build
  - make test

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: ./build/libuast-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    tags: true
